"""empty message

Revision ID: 3ca902f7d1dd
Revises:
Create Date: 2025-01-25 15:34:36.759916

"""


import os
environment = os.environ.get("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca902f7d1dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chord_family', sa.String(length=50), nullable=True),
    sa.Column('chord_name', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('details_of_course', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=50), nullable=False),
    sa.Column('key_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progression_name', sa.String(length=50), nullable=True),
    sa.Column('progression_type', sa.String(length=50), nullable=True),
    sa.Column('progression_style', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=40), nullable=True),
    sa.Column('review_content', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('root', sa.String(length=5), nullable=True),
    sa.Column('flats', sa.Integer(), nullable=True),
    sa.Column('sharps', sa.Integer(), nullable=True),
    sa.Column('pulls_to', sa.String(length=255), nullable=True),
    sa.Column('pulls_from', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_key', sa.String(length=40), nullable=True),
    sa.Column('song', sa.String(length=100), nullable=True),
    sa.Column('artist', sa.String(length=40), nullable=True),
    sa.Column('chords_used', sa.String(length=40), nullable=True),
    sa.Column('progression_used', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('song_chords',
    sa.Column('chord_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chord_id'], ['chords.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('chord_id', 'song_id')
    )
    op.create_table('song_keys',
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['keys.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('key_id', 'song_id')
    )
    op.create_table('song_progressions',
    sa.Column('progression_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['progression_id'], ['progressions.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('progression_id', 'song_id')
    )
    op.create_table('user_courses',
    sa.Column('courses_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('courses_id', 'users_id')
    )


    if environment == "production":
        op.execute(f"ALTER TABLE chords SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE courses SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE keys SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE progressions SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE scales SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE songs SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE song_chords SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE song_keys SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE song_progressions SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE user_courses SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_courses')
    op.drop_table('song_progressions')
    op.drop_table('song_keys')
    op.drop_table('song_chords')
    op.drop_table('users')
    op.drop_table('songs')
    op.drop_table('scales')
    op.drop_table('reviews')
    op.drop_table('progressions')
    op.drop_table('keys')
    op.drop_table('courses')
    op.drop_table('chords')
    # ### end Alembic commands ###
