"""empty message

Revision ID: 971f701cf532
Revises: 
Create Date: 2025-01-13 22:09:45.199112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971f701cf532'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chord_name', sa.String(length=50), nullable=False),
    sa.Column('chord_key', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chord_name')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('details_of_course', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_name'),
    sa.UniqueConstraint('details_of_course')
    )
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_name')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('pulls_to', sa.String(length=100), nullable=True),
    sa.Column('pulls_from', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('progressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progression_name', sa.String(length=50), nullable=False),
    sa.Column('progression_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('progression_name')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_title', sa.String(length=40), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_key', sa.String(length=40), nullable=False),
    sa.Column('song', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=40), nullable=False),
    sa.Column('chords_used', sa.String(length=40), nullable=False),
    sa.Column('progression_used', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'course_id')
    )
    op.create_table('course_reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('review_id', 'course_id')
    )
    op.create_table('lesson_chords',
    sa.Column('chord_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('except_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chord_id'], ['chords.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('chord_id', 'lesson_id')
    )
    op.create_table('lesson_keys',
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['keys.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('key_id', 'lesson_id')
    )
    op.create_table('lesson_progressions',
    sa.Column('progression_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['progression_id'], ['progressions.id'], ),
    sa.PrimaryKeyConstraint('progression_id', 'lesson_id')
    )
    op.create_table('lesson_songs',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('except_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'lesson_id')
    )
    op.create_table('song_chords',
    sa.Column('chord_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chord_id'], ['chords.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('chord_id', 'song_id')
    )
    op.create_table('song_keys',
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['keys.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('key_id', 'song_id')
    )
    op.create_table('song_progressions',
    sa.Column('progression_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('except_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['progression_id'], ['progressions.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('progression_id', 'song_id')
    )
    op.create_table('user_courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_courses')
    op.drop_table('song_progressions')
    op.drop_table('song_keys')
    op.drop_table('song_chords')
    op.drop_table('lesson_songs')
    op.drop_table('lesson_progressions')
    op.drop_table('lesson_keys')
    op.drop_table('lesson_chords')
    op.drop_table('course_reviews')
    op.drop_table('course_lessons')
    op.drop_table('users')
    op.drop_table('songs')
    op.drop_table('reviews')
    op.drop_table('progressions')
    op.drop_table('lessons')
    op.drop_table('keys')
    op.drop_table('courses')
    op.drop_table('chords')
    # ### end Alembic commands ###
